### PR TITLE
Add `core-js` implementation

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by ljharb** [comment]
It is very irresponsible to publish this as a polyfill; it’s not even stage 2 yet, and the name “unThis” will never achieve consensus.

**Comment by zloirock** [comment]
It's unlogical to write it each time when I add a polyfill for an early-stage proposal. Please, avoid it next time. It's only for experimentation and changing name in the future is additional protection from possible problems.

**Comment by ljharb** [comment]
I didn't write it each time; you made similar PRs on two other pre-stage-3 proposals. This one, however, is particularly dangerous, and I think it would be quite harmful to link to it from the proposal's readme.

"Only for experimentation" is irrelevant; modifying builtins in nonstandard ways harms the web, for whatever purpose.

**Comment by zloirock** [comment]
Maybe not each time, but you write it too often. I have more experience in polyfills and web stability than you, so please don't say me what should I do and what I should not do.

>  "Only for experimentation" is irrelevant

This is an unfounded statement. Without pre-stage 3 polyfills you cant touch the new functionality and check how it works in real life, with other new features. Without it, too many proposals could have the required feedback too late.

> harms the web

Some of your cases like [this](https://github.com/tarruda/has/pull/17) make much more harm for the web than current.

**Comment by ljharb** [comment]
It's not an unfounded statement. Prior to stage 3, all sorts of experimentation can be done without needing to install anything into the environment, and is often done. 

The TC39 process doesn't *want* that feedback until stage 3 - that is what that stage is for.

**Comment by zloirock** [comment]
Stage 3 presupposes feedback from JS engine implementors and mass users. As you could see [in the process document](https://tc39.es/process-document/), polyfills are expected on stage-1 and they help for further advance.

**Comment by ljharb** [comment]
Thanks; I'll update the process document so it no longer incorrectly indicates this about polyfills.

**Comment by zloirock** [comment]
Please do not impose your personal opinion on others.

**Comment by ljharb** [comment]
It's the entire committee's opinion; it's just not correctly documented - probably because it didn't occur to anyone back in 2015 that polyfill authors would need to be told to wait until stage 3 to publish.

**Comment by zloirock** [comment]
It seems that the сommittee is not agree with you https://github.com/tc39/process-document/pull/33

**Comment by ljharb** [comment]
I think you're misunderstanding the comment. Either way, let's keep the immature gloating about decisions off of github, thanks.

**Comment by js-choi** [comment]
Thank you for your work on this, @zloirock. However, in this particular case, I would like to avoid people from using any public polyfills for now, because this proposal is currently very unstable. In particular, its very name, “un-this”, is unstable and likely to change (#1). 

We can open this pull request back up once the proposal settles more. Thank you again for your work.

**Comment by zloirock** [comment]
@ljharb how else should I react to an attempt to significantly degrade the language development process?

**Comment by ljharb** [comment]
If folks actually involved in that process inside TC39 think it's degrading it, then they are free to bring it up in plenary - but that has not been the majority consensus in the room on the topic in the 7 years I've been on the committee.

**Comment by zloirock** [comment]
@js-choi, since it's only for experiments, instability of the name is not a big problem, however ok, let's wait for stabilization -)

**Pull request closed without merging**
